// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class Accrual
    {
        public int IdAccrual { get; set; }
        public int IdDeposit { get; set; }
        public DateTime DateAccrual { get; set; }
        public string Amount { get; set; }

        public virtual Deposit IdDepositNavigation { get; set; }
    }
}