// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Accrual")]
    public partial class Accrual
    {
        [Key]
        [Column("id_accrual")]
        public int IdAccrual { get; set; }
        [Column("id_deposit")]
        public int IdDeposit { get; set; }
        [Column("date_accrual", TypeName = "date")]
        public DateTime DateAccrual { get; set; }
        [Required]
        [Column("amount")]
        [StringLength(10)]
        public string Amount { get; set; }

        [ForeignKey(nameof(IdDeposit))]
        [InverseProperty(nameof(Deposit.Accruals))]
        public virtual Deposit IdDepositNavigation { get; set; }
    }
}