// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("BankAccount")]
    public partial class BankAccount
    {
        public BankAccount()
        {
            Credits = new HashSet<Credit>();
            Deposits = new HashSet<Deposit>();
        }

        [Key]
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdCurrency { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOpen { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateClose { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }
        [StringLength(20)]
        public string AccountType { get; set; }

        [ForeignKey(nameof(IdClient))]
        [InverseProperty(nameof(Client.BankAccounts))]
        public virtual Client IdClientNavigation { get; set; }
        [ForeignKey(nameof(IdCurrency))]
        [InverseProperty(nameof(Currency.BankAccounts))]
        public virtual Currency IdCurrencyNavigation { get; set; }
        [InverseProperty(nameof(Credit.IdAccountNavigation))]
        public virtual ICollection<Credit> Credits { get; set; }
        [InverseProperty(nameof(Deposit.IdAccountNavigation))]
        public virtual ICollection<Deposit> Deposits { get; set; }
    }
}