// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class BankAccount
    {
        public BankAccount()
        {
            Credits = new HashSet<Credit>();
            Deposits = new HashSet<Deposit>();
            Operations = new HashSet<Operation>();
        }

        public int IdAccount { get; set; }
        public int IdClient { get; set; }
        public string AccountType { get; set; }
        public int IdCurrency { get; set; }
        public DateTime DateOpen { get; set; }
        public DateTime? DateClose { get; set; }
        public decimal Amount { get; set; }

        public virtual Client IdClientNavigation { get; set; }
        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
    }
}