// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Client")]
    public partial class Client
    {
        public Client()
        {
            BankAccounts = new HashSet<BankAccount>();
        }

        [Key]
        [Column("id_client")]
        public int IdClient { get; set; }
        [Required]
        [Column("login")]
        [StringLength(100)]
        public string Login { get; set; }
        [Required]
        [Column("password")]
        [StringLength(24)]
        public string Password { get; set; }
        [Required]
        [Column("address")]
        [StringLength(120)]
        public string Address { get; set; }
        [Required]
        [Column("tel_number")]
        [StringLength(15)]
        public string TelNumber { get; set; }

        [InverseProperty("IdEdrpouNavigation")]
        public virtual LegalPerson LegalPerson { get; set; }
        [InverseProperty("IdPersonNavigation")]
        public virtual PhysicalPerson PhysicalPerson { get; set; }
        [InverseProperty(nameof(BankAccount.IdClientNavigation))]
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
    }
}