// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class Credit
    {
        public Credit()
        {
            Repayments = new HashSet<Repayment>();
        }

        public int IdCredit { get; set; }
        public int IdAccount { get; set; }
        public decimal PercentCredit { get; set; }
        public decimal Amount { get; set; }
        public DateTime DateCredit { get; set; }
        public bool Status { get; set; }

        public virtual BankAccount IdAccountNavigation { get; set; }
        public virtual ICollection<Repayment> Repayments { get; set; }
    }
}