// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Currency")]
    public partial class Currency
    {
        public Currency()
        {
            BankAccounts = new HashSet<BankAccount>();
            ExchangeRates = new HashSet<ExchangeRate>();
        }

        [Key]
        [Column("id_currency")]
        public int IdCurrency { get; set; }
        [Required]
        [Column("name")]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [Column("short_name")]
        [StringLength(10)]
        public string ShortName { get; set; }

        [InverseProperty(nameof(BankAccount.IdCurrencyNavigation))]
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        [InverseProperty(nameof(ExchangeRate.IdCurrencyNavigation))]
        public virtual ICollection<ExchangeRate> ExchangeRates { get; set; }
    }
}