// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Deposit")]
    public partial class Deposit
    {
        public Deposit()
        {
            Accruals = new HashSet<Accrual>();
        }

        [Key]
        public int Id { get; set; }
        public int? IdAccount { get; set; }
        [Column(TypeName = "decimal(6, 2)")]
        public decimal PercentDeposit { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDateDeposit { get; set; }
		[Column(TypeName = "date")]
		public DateTime EndDateDeposit { get; set; }
		[Required]
		[StringLength(20)]
		public string TypeOfDeposit { get; set; }
        public bool Status { get; set; }

		[ForeignKey(nameof(IdAccount))]
        [InverseProperty(nameof(BankAccount.Deposits))]
        public virtual BankAccount IdAccountNavigation { get; set; }
        [InverseProperty(nameof(Accrual.IdDepositNavigation))]
        public virtual ICollection<Accrual> Accruals { get; set; }
    }
}