// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class Deposit
    {
        public Deposit()
        {
            Accruals = new HashSet<Accrual>();
        }

        public int IdDeposit { get; set; }
        public int IdAccount { get; set; }
        public decimal PercentDeposit { get; set; }
        public decimal Amount { get; set; }
        public DateTime DateDeposit { get; set; }
        public bool Status { get; set; }

        public virtual BankAccount IdAccountNavigation { get; set; }
        public virtual ICollection<Accrual> Accruals { get; set; }
    }
}