// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class LegalPerson
    {
        public int IdEdrpou { get; set; }
        public string Name { get; set; }
        public string OwnershipType { get; set; }
        public string Director { get; set; }

        public virtual Client IdEdrpouNavigation { get; set; }
    }
}