// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("LegalPerson")]
    public partial class LegalPerson
    {
        [Key]
        [Column("id_edrpou")]
        public int IdEdrpou { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [Column("ownership_type")]
        [StringLength(20)]
        public string OwnershipType { get; set; }
        [Required]
        [Column("director")]
        [StringLength(50)]
        public string Director { get; set; }

        [ForeignKey(nameof(IdEdrpou))]
        [InverseProperty(nameof(Client.LegalPerson))]
        public virtual Client IdEdrpouNavigation { get; set; }
    }
}