// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Operation")]
    public partial class Operation
    {
        [Key]
        [Column("operation_time", TypeName = "datetime")]
        public DateTime OperationTime { get; set; }
        [Key]
        [Column("id_account")]
        public int IdAccount { get; set; }
        [Required]
        [Column("type_operation")]
        [StringLength(30)]
        public string TypeOperation { get; set; }
        [Column("amount", TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }

        [ForeignKey(nameof(IdAccount))]
        [InverseProperty(nameof(BankAccount.Operations))]
        public virtual BankAccount IdAccountNavigation { get; set; }
    }
}