// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("PhysicalPerson")]
    public partial class PhysicalPerson
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(2)]
        public string PassportSeries { get; set; }
        [Required]
        [StringLength(10)]
        public string PassportNumber { get; set; }
        [Required]
        [StringLength(10)]
        public string IdentificationNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string Surname { get; set; }
        [Required]
        [StringLength(40)]
        public string Name { get; set; }
        [Required]
        [StringLength(80)]
        public string Patronymic { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(Client.PhysicalPerson))]
        public virtual Client IdNavigation { get; set; }
    }
}