// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("PhysicalPerson")]
    public partial class PhysicalPerson
    {
        [Key]
        [Column("id_person")]
        public int IdPerson { get; set; }
        [Required]
        [Column("passport_series")]
        [StringLength(2)]
        public string PassportSeries { get; set; }
        [Required]
        [Column("passport_number")]
        [StringLength(10)]
        public string PassportNumber { get; set; }
        [Required]
        [Column("identification_number")]
        [StringLength(10)]
        public string IdentificationNumber { get; set; }
        [Required]
        [Column("surname")]
        [StringLength(50)]
        public string Surname { get; set; }
        [Required]
        [Column("name")]
        [StringLength(40)]
        public string Name { get; set; }
        [Required]
        [Column("patronymic")]
        [StringLength(80)]
        public string Patronymic { get; set; }

        [ForeignKey(nameof(IdPerson))]
        [InverseProperty(nameof(Client.PhysicalPerson))]
        public virtual Client IdPersonNavigation { get; set; }
    }
}