// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationCore.Entity
{
    [Table("Repayment")]
    public partial class Repayment
    {
        [Key]
        [Column("id_repayment")]
        public int IdRepayment { get; set; }
        [Column("id_credit")]
        public int IdCredit { get; set; }
        [Column("date_repayment", TypeName = "date")]
        public DateTime DateRepayment { get; set; }
        [Column("amount", TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }

        [ForeignKey(nameof(IdCredit))]
        [InverseProperty(nameof(Credit.Repayments))]
        public virtual Credit IdCreditNavigation { get; set; }
    }
}