// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore
{
    public partial class Repayment
    {
        public int IdRepayment { get; set; }
        public int IdCredit { get; set; }
        public DateTime DateRepayment { get; set; }
        public decimal Amount { get; set; }

        public virtual Credit IdCreditNavigation { get; set; }
    }
}